NAME: TIMotion
NUM_LAYERS: 5
NUM_HEADS: 16
DROPOUT: 0.1
INPUT_DIM: 262
LATENT_DIM: 512
FF_SIZE: 2048
ACTIVATION: gelu
CHECKPOINT: #
LPA: True
conv_layers: 1
dilation_rate: 1
norm: AdaLN

DIFFUSION_STEPS: 1000
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 700

CONTROL: text
STRATEGY: ddim50
CFG_WEIGHT: 3.5
